### ISSUE TITLE
Add relay slots / basic QoS

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-connect#208]
## Context

Hopr nodes that are willing to become a relay for other can announce themself on-chain. Other nodes can then try to contact these nodes in order announce to other nodes that they are available "behind" these nodes.

Since these nodes have limited resources, they should only allow a limited number number of relay requests.

## Desired feature

Define an upper bound of simultaneous relay connection and deny all further relay requests

- Add an additional error, showing the relay "is full"
- Handle this error at the client and try a different relay

**Comment by tolbrino** [comment]
Client-side entrypoint: https://github.com/hoprnet/hopr-connect/blob/main/src/relay/connection.ts
Server-side entrypoint: https://github.com/hoprnet/hopr-connect/blob/main/src/relay/context.ts
