### ISSUE TITLE
Unable to bind to any IP when multiple NIC interfaces exists in the host

### ISSUE THREAD

**Issue by ptrnull** [hoprnet/hopr-connect#21]
## Expected Behavior

When running the hopr/chat into a server with multiple NICS and IPs and one of the IP is provided (not 0.0.0.0) the code should be able to identify what NIC has that IP and bind to that IP.

## Current Behavior

When running the hopr/chat into a server with multiple NICS and IPs and one of the IP is provided the code is not able to bind to any address, it gives the error "Unable to detect to which interface we should listen" even if the ip  0.0.0.0 is provided for binding to all the addresses. 

## (Optional) Possible Solution

(Write your answer here.)

## Steps to Reproduce

The server has more than one NIC and each one has an IP assigned.
1. docker pull hopr/chat
2.docker run -v $(pwd)/db:/app/db \
-e HOST_IPV4=1.2.3.4:9091 \
-e BOOTSTRAP_SERVERS=/ip4/34.65.219.148/tcp/9091/p2p/16Uiu2HAkwSEiK819yvnG84pNFsqXkpFX4uiCaNSwADnmYeAfctRn \
-e ETHEREUM_PROVIDER=wss://kovan.infura.io/ws/v3/f7240372c1b442a6885ce9bb825ebc36 \
-p 9091:9091 -it hopr/chat -p switzerland

3.
4.

## Context (Environment)
Not able to run the node in a server with multiple IPs.

(Write your answer here.)

## Detailed Description

(Write your answer here.)

## (Optional) Possible Implementation

(Write your answer here.)

**Comment by jjperezaguinaga** [comment]
@ptrnull  Hi! We transferred your issue to this repository, thanks!

**Comment by ptrnull** [comment]
Great!, thanks @jjperezaguinaga !

**Comment by jjperezaguinaga** [comment]
@robertkiel can you provide an update on this? Ideally, let's create a milestone roadmap so @ptrnull and other project watchers can have an idea when features will be added, if at all.

**Comment by robertkiel** [comment]
First support got included in #42 , need to test on multiple machines
