### ISSUE TITLE
Improve pushPromise functionality

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-connect#275]
https://github.com/hoprnet/hopr-connect/blob/48c4b36df1b82e6d20b747c5c3416365e65b6e2f/src/relay/connection.ts#L286-L293

This can lead to ambiguous values of resolvedPromiseName.

E.g. firstPromise resolves, meanwhile there is some await or setTimeout and *another* promise resolves which sets the variable to a different value.

It could be beneficial to change the logic such that

```
const result = await Promise.race(promises)
```

where `result` is set to:
```ts
{
  name: `description of promise`
  value: ReturnValue
}
```

This could also be used to turn the `while (true)` loop into a proper finite state machine

**Comment by andreykiryushkin** [comment]
That's a huge refactoring of the whole state machine logics and I want to establish reliable test suite first before diving into this well @robertkiel
